---
name: "send_heartbeat_timer"
pack: "opsgenie"
description:
enabled: false

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
      unit: "minutes"
      delta: 12

action:
  ref: "chatops.post_message"
  parameters:
    user: "{{system.opsgenie_timer_hb_user}}"
    message: "opsgenie heartbeat send {{system.opsgenie_timer_hb_name}}{~}"
    channel: "{{system.opsgenie_timer_hb_channel}}"
